version: '3'
services:
  website:
    env_file: ../.env
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - /usr/src/app/.yarn/cache
      - /usr/src/app/node_modules
      - /usr/src/app/apps/website/node_modules
      - ../:/usr/src/app
    depends_on:
      - db
    links:
      - 'db:db'
    command: /bin/bash -c 'yarn && yarn dev'

  db:
    container_name: tlk_db
    env_file: ../.env
    image: postgres:15.3-alpine3.18
    restart: always
    volumes:
      - tlk_data:/var/lib/posgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120

  proxy:
    env_file: ../.env
    image: caddy:2.6.4-alpine
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/usr/local/etc/caddy/certs
      - tlk_caddy_data:/data
      - tlk_caddy_config:/config

volumes:
  tlk_data:
  tlk_caddy_data:
  tlk_caddy_config:
